server:
  port: 5008
spring:
  cloud:
    gateway:
      routes:
        - id: testservice_route
          uri: http://localhost:61807
          order: 2
          predicates:
            - Path=/testservice/{path}
          filters:
            - AddRequestHeader=apikey, 123
            - SetPath=/{path}
            - Auth