server:
  port: 5008
spring:
  cloud:
    gateway:
      routes:
        - id: verificationservice_addverification_route
          uri: http://172.17.0.16:8002
          order: 1
          predicates:
            - Path=/verificationservice/verification/v1
            - Method=POST
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168906c7e9f002
            - SetPath=/api/verification/v1
        - id: testservice_route
          uri: http://localhost:61807
          order: 2
          predicates:
            - Path=/testservice/{path}
          filters:
            - AddRequestHeader=apikey, 123
            - SetPath=/{path}
            - Auth
        - id: userservice_checkuser_route
          uri: http://172.17.0.16:8001
          order: 3
          predicates:
            - Path=/userservice/checkuser/v1
            - Method=POST
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f001
            - SetPath=/api/user/check/v1
        - id: userservice_checkuser_route
          uri: http://172.17.0.16:8001
          order: 4
          predicates:
            - Path=/userservice/adduser/v1
            - Method=POST
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f001
            - SetPath=/api/user/v1
        - id: userservice_getuser_route
          uri: http://172.17.0.16:8001
          order: 5
          predicates:
            - Path=/userservice/getuser/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f001
            - SetPath=/api/user/v1
            - Auth
        - id: jpservice_addquestion_route
          uri: http://172.17.0.16:8003
          order: 6
          predicates:
            - Path=/jpservice/addquestion/v1
            - Method=POST
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/question/v1
            - Auth
        - id: jpservice_updatequestion_route
          uri: http://172.17.0.16:8003
          order: 7
          predicates:
            - Path=/jpservice/updatequestion/v1
            - Method=PUT
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/question/v1
            - Auth
        - id: jpservice_getquestion_route
          uri: http://172.17.0.16:8003
          order: 8
          predicates:
            - Path=/jpservice/getquestion/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/question/v1
        - id: jpservice_getquestion_route
          uri: http://172.17.0.16:8003
          order: 8
          predicates:
            - Path=/jpservice/getquestions/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/questions/v1
        - id: jpservice_addrecommend_route
          uri: http://172.17.0.16:8003
          order: 9
          predicates:
            - Path=/jpservice/addrecommend/v1
            - Method=POST
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/recommend/v1
            - Auth
        - id: jpservice_updaterecommend_route
          uri: http://172.17.0.16:8003
          order: 9
          predicates:
            - Path=/jpservice/updaterecommend/v1
            - Method=PUT
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/recommend/v1
            - Auth
        - id: jpservice_getrecommend_route
          uri: http://172.17.0.16:8003
          order: 10
          predicates:
            - Path=/jpservice/getrecommend/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/recommend/v1
        - id: jpservice_getrecommends_route
          uri: http://172.17.0.16:8003
          order: 11
          predicates:
            - Path=/jpservice/getrecommends/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/recommends/v1
        - id: jpservice_addcomment_route
          uri: http://172.17.0.16:8003
          order: 12
          predicates:
            - Path=/jpservice/addcomment/v1
            - Method=POST
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/comment/v1
            - Auth
        - id: jpservice_updatecomment_route
          uri: http://172.17.0.16:8003
          order: 13
          predicates:
            - Path=/jpservice/updatecomment/v1
            - Method=PUT
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/comment/v1
            - Auth
        - id: jpservice_getcommend_route
          uri: http://172.17.0.16:8003
          order: 13
          predicates:
            - Path=/jpservice/getcomment/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/comment/v1
        - id: jpservice_getcomments_route
          uri: http://172.17.0.16:8003
          order: 14
          predicates:
            - Path=/jpservice/getcomments/v1
            - Method=GET
          filters:
            - AddRequestHeader=apikey, 63e960be918111e799168826c7e9f003
            - SetPath=/api/comments/v1